syntax = "proto3";

package gamepb.qqvippb;

import "corepb.proto";

// ============ QQ会员服务 ============

// --- 刷新QQ会员信息 ---
message RefreshVipInfoRequest {}
message RefreshVipInfoReply {}

// --- 获取QQ会员礼包状态 ---
message GetQQVipRewardsStatusRequest {}

message QQVipRewardConfig {
    repeated corepb.Item rewards = 2;
    int32 vip_type = 5;     // 1: QQ会员，2: 超级会员
}

message GetQQVipRewardsStatusReply {
    repeated QQVipRewardConfig reward_configs = 5;
}

// --- 领取QQ会员礼包 ---
message ClaimQQVipRewardsRequest {
    repeated int32 vip_types = 1;  // 1: QQ会员，2: 超级会员；每次只提交一个礼包类型
}

message ClaimQQVipRewardsReply {
    repeated corepb.Item items = 3;  // 奖励物品列表
}
